markdown: kramdown
exclude: ["README.md", "Tumblr"]
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
paginate: 5
paginate_path: /page/:num
permalink: /:title
url: usabilityreport.de/
