title: Usability Report | Usability & User Experience Blog
description: Auf Usability Report erscheinen wöchentlich Artikel mit Tipps und Informationen für angehende Usabilty & User Experience Experten.

markdown: kramdown
highlighter: rouge
exclude: ["README.md", "Tumblr"]

safe: false
paginate: 5
paginate_path: /page/:num
permalink: /:title
plugins:
  # - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
# url: http://www.usabilityreport.de
