markdown: kramdown
highlighter: rouge
exclude: ["README.md", "Tumblr"]

paginate: 5
paginate_path: /page/:num
permalink: /:title
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
url: http://www.usabilityreport.de
